### PR TITLE
Issue #1 fix boolean minifying

### PR DESCRIPTION
**Pull request by Ovsyanka**
I just added option (https://github.com/mishoo/UglifyJS2#compressor-options) to compressor to disable boolean converting. Now it not convert true/false to !0/!1.

### CODE REVIEW

**Comment by Ovsyanka** [comment]
I fix it with less influense on other parts of functionality. But, maybe it will be better to delete whole "compressing" part? As i think - that part can't really modify json object because it is object and his property names can't be changed. I am talking about this:

``` js
var compressor = UglifyJS.Compressor();
ast = ast.transform(compressor);
```

When i deleted this i am not noticed about any changes in my case.

**Comment by tssajo** [comment]
Thanks for the PR! I was looking for an option yesterday on the UglifyJS site to disable the boolean optimization somehow, but I could not find the option. But you did, thank you!

If I remove those two lines, then we won't be using UglifyJS.Compressor at all. How would this program be a minifier then? I thought that the Compressor method does the actual minification. No?

**Comment by Ovsyanka** [comment]
Just try it and you will see =)
I think that compress mean shorting variable names and etc. Removing spaces and etc. working without compressing. Maybe it have not sense to use uglifyer at all if you want just remove spaces in json.

**Comment by tssajo** [comment]
You are right. I did some testing and it turns out that we do not need to call UglifyJS.Compressor at all when minifying JSON data. So I turned off the `compress` option in `cli.js` and did some testing. It looks to me that the program still works and producing the exact same output as before. Thanks for the suggestion!

**Comment by Ovsyanka** [comment]
I glad to help you )

**Pull request merged**
